/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package patientinfor;

import java.sql.*;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ADMIN
 */
public class dlgThongke extends javax.swing.JDialog {
    
    DefaultTableModel model = new DefaultTableModel();
    Connection conn = null;
    ResultSet rs = null;
    /**
     * Creates new form dlgThongke
     */
    public dlgThongke(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        try {
            setTitle("Thong Ke!");
            Class.forName("com.microsoft.sqlserver.jdbc.SQLServerDriver");
            conn = DriverManager.getConnection("jdbc:sqlserver://localhost:1433;databaseName=PI", "sa", "123456");

        } catch (Exception e) {
            e.printStackTrace();
        }
        initComponents();
    }
    private void loadClass(){
        try {
            model = new DefaultTableModel();
            TableTKBN.setModel(model);
            String sSelect = "SELECT ID,HoTen,DiaChi,Tuoi,GioiTinh,Khoa,TrieuChung,Benh,NgayNhap,NgayRa,NhapHoacKhong FROM tblBenhNhan";
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(sSelect); 
            
            //add Column
            ResultSetMetaData meta = rs.getMetaData();
            for(int i=1;i<=meta.getColumnCount();i++){
                String sName = meta.getColumnName(i);
                model.addColumn(sName);
            }
            //add row
            while(rs.next()){
                Vector v = new Vector();
                v.addElement(rs.getString(1));
                v.addElement(rs.getString(2));
                v.addElement(rs.getString(3));
                v.addElement(rs.getString(4));
                v.addElement(rs.getString(5));
                v.addElement(rs.getString(6));
                v.addElement(rs.getString(7));
                v.addElement(rs.getString(8));
                v.addElement(rs.getString(9));
                v.addElement(rs.getString(10));
                v.addElement(rs.getString(11));
                
                model.addRow(v);
            }
           // rs.close();
            stmt.close();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JScrollPane = new javax.swing.JScrollPane();
        TableTKBN = new javax.swing.JTable();
        btnConnert = new javax.swing.JButton();
        btnExxit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        TableTKBN.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        JScrollPane.setViewportView(TableTKBN);

        btnConnert.setText("Connert");
        btnConnert.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnConnertActionPerformed(evt);
            }
        });

        btnExxit.setText("Exit");
        btnExxit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExxitActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(147, 147, 147)
                        .addComponent(btnConnert)
                        .addGap(44, 44, 44)
                        .addComponent(btnExxit))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 860, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(JScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnConnert)
                    .addComponent(btnExxit))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnExxitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExxitActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_btnExxitActionPerformed

    private void btnConnertActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnConnertActionPerformed
        // TODO add your handling code here:
        try {
            loadClass();
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_btnConnertActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(dlgThongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(dlgThongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(dlgThongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(dlgThongke.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the dialog
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                dlgThongke dialog = new dlgThongke(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane JScrollPane;
    private javax.swing.JTable TableTKBN;
    private javax.swing.JButton btnConnert;
    private javax.swing.JButton btnExxit;
    // End of variables declaration//GEN-END:variables
}
